# This is a config for E2B sandbox template.
# You can use template ID (psdhv3ddx93bt1lyrcuf) or template name (pixe-nextjs-test-912) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("pixe-nextjs-test-912") # Sync sandbox
# sandbox = await AsyncSandbox.create("pixe-nextjs-test-912") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('pixe-nextjs-test-912')

team_id = "0c1c0952-6bc4-48bd-8d49-bcb17f792369"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "pixe-nextjs-test-912"
template_id = "psdhv3ddx93bt1lyrcuf"
